#!/bin/bash
#Author: VASANTH
#Date: May 2 2021

echo "THIS SCRIPT WILL CREATE A CONTAINER NGINX:1.19.10"
echo "--------------------"
sleep 1
echo "IF ANY FATAL ERROR OCCURED CONTAINER WILL RESTARTS AUTOMATICALLY"
echo "--------------------"

docker-compose -f ex2-compose.yml up

sleep 1
echo
echo "-------------------"
echo "CONTAINER EXITED SINCE CTRL+C IS PRESSED"
echo "--------------------"
