#!/bin/bash
#Date: May 4 2021
#Author: Vasanth
#Desc: CHANGE IMAGE OF NGINX TO NGINX:1.20.0 AND RECORD THE CAUSE OF CHANGE

echo "-----------------"
echo "STARTING THE DEPLOYMENT FIRST"
echo "-----------------"
kubectl create -f kubex5-deployment.yaml
echo "-----------------"
echo "-----------------"
echo "SETTING NEW IMAGE VERSION AND RECORDING IT FOR web-deploy DEVELOPMENT"
echo "-----------------"
kubectl set image deployment web-deploy nginx=nginx:1.20.0 --record 
echo "-----------------"
echo "RECORDED HISTORY"
echo "-----------------"
kubectl rollout history deployment web-deploy
echo "-----------------"
echo "-----------------"
echo "-----------------"
echo "ALL DETAILS"
echo "-----------------"
kubectl get all
