apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    name: redis-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: vasanthstorage
  accessModes:
    - ReadWriteOnce
